# Generated by Django 5.0.1 on 2024-01-14 11:17

import django.utils.timezone
import todo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_task_due_date_alter_task_due_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=todo.models.default_due_date),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
